// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/data.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SideDishes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SideDishes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SideDishes with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SideDishesMultiError, or
// nil if none found.
func (m *SideDishes) ValidateAll() error {
	return m.validate(true)
}

func (m *SideDishes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Remark

	if all {
		switch v := interface{}(m.GetCreateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SideDishesValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SideDishesValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SideDishesValidationError{
				field:  "CreateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SideDishesValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SideDishesValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SideDishesValidationError{
				field:  "UpdateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SideDishesMultiError(errors)
	}

	return nil
}

// SideDishesMultiError is an error wrapping multiple validation errors
// returned by SideDishes.ValidateAll() if the designated constraints aren't met.
type SideDishesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SideDishesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SideDishesMultiError) AllErrors() []error { return m }

// SideDishesValidationError is the validation error returned by
// SideDishes.Validate if the designated constraints aren't met.
type SideDishesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SideDishesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SideDishesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SideDishesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SideDishesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SideDishesValidationError) ErrorName() string { return "SideDishesValidationError" }

// Error satisfies the builtin error interface
func (e SideDishesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSideDishes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SideDishesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SideDishesValidationError{}

// Validate checks the field values on Dishes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Dishes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Dishes with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DishesMultiError, or nil if none found.
func (m *Dishes) ValidateAll() error {
	return m.validate(true)
}

func (m *Dishes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Logo

	// no validation rules for Remark

	if all {
		switch v := interface{}(m.GetCreateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DishesValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DishesValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DishesValidationError{
				field:  "CreateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DishesValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DishesValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DishesValidationError{
				field:  "UpdateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DishesMultiError(errors)
	}

	return nil
}

// DishesMultiError is an error wrapping multiple validation errors returned by
// Dishes.ValidateAll() if the designated constraints aren't met.
type DishesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DishesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DishesMultiError) AllErrors() []error { return m }

// DishesValidationError is the validation error returned by Dishes.Validate if
// the designated constraints aren't met.
type DishesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DishesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DishesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DishesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DishesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DishesValidationError) ErrorName() string { return "DishesValidationError" }

// Error satisfies the builtin error interface
func (e DishesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDishes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DishesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DishesValidationError{}
