// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: api/v1/dishes.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes *Dishes `protobuf:"bytes,1,opt,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *UpdateDishesResponse) Reset() {
	*x = UpdateDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishesResponse) ProtoMessage() {}

func (x *UpdateDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishesResponse.ProtoReflect.Descriptor instead.
func (*UpdateDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDishesResponse) GetDishes() *Dishes {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type UpdateDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo   string `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Remark string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *UpdateDishesRequest) Reset() {
	*x = UpdateDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishesRequest) ProtoMessage() {}

func (x *UpdateDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishesRequest.ProtoReflect.Descriptor instead.
func (*UpdateDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDishesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDishesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDishesRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *UpdateDishesRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DelDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelDishesResponse) Reset() {
	*x = DelDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelDishesResponse) ProtoMessage() {}

func (x *DelDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelDishesResponse.ProtoReflect.Descriptor instead.
func (*DelDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{2}
}

type DelDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelDishesRequest) Reset() {
	*x = DelDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelDishesRequest) ProtoMessage() {}

func (x *DelDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelDishesRequest.ProtoReflect.Descriptor instead.
func (*DelDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{3}
}

func (x *DelDishesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDishesRequest) Reset() {
	*x = GetDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesRequest) ProtoMessage() {}

func (x *GetDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesRequest.ProtoReflect.Descriptor instead.
func (*GetDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{4}
}

func (x *GetDishesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes *Dishes `protobuf:"bytes,1,opt,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *GetDishesResponse) Reset() {
	*x = GetDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDishesResponse) ProtoMessage() {}

func (x *GetDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDishesResponse.ProtoReflect.Descriptor instead.
func (*GetDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{5}
}

func (x *GetDishesResponse) GetDishes() *Dishes {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type ListDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes []*Dishes `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	Total  int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListDishesResponse) Reset() {
	*x = ListDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDishesResponse) ProtoMessage() {}

func (x *ListDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDishesResponse.ProtoReflect.Descriptor instead.
func (*ListDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{6}
}

func (x *ListDishesResponse) GetDishes() []*Dishes {
	if x != nil {
		return x.Dishes
	}
	return nil
}

func (x *ListDishesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PageIndex int64  `protobuf:"varint,888,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize  int64  `protobuf:"varint,889,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListDishesRequest) Reset() {
	*x = ListDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDishesRequest) ProtoMessage() {}

func (x *ListDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDishesRequest.ProtoReflect.Descriptor instead.
func (*ListDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{7}
}

func (x *ListDishesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDishesRequest) GetPageIndex() int64 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListDishesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Logo   string `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Remark string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *CreateDishesRequest) Reset() {
	*x = CreateDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDishesRequest) ProtoMessage() {}

func (x *CreateDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDishesRequest.ProtoReflect.Descriptor instead.
func (*CreateDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDishesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDishesRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *CreateDishesRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes *Dishes `protobuf:"bytes,1,opt,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *CreateDishesResponse) Reset() {
	*x = CreateDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_dishes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDishesResponse) ProtoMessage() {}

func (x *CreateDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_dishes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDishesResponse.ProtoReflect.Descriptor instead.
func (*CreateDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_dishes_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDishesResponse) GetDishes() *Dishes {
	if x != nil {
		return x.Dishes
	}
	return nil
}

var File_api_v1_dishes_proto protoreflect.FileDescriptor

var file_api_v1_dishes_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x64,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22,
	0x89, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x05, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x13, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2b, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x06, 0x64, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x64, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x22, 0x77, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0xf8, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0xf9, 0x06, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02,
	0x28, 0x01, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x67, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x05, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x32, 0xe2, 0x03, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01,
	0x2a, 0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x2f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x57, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12,
	0x5a, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1a, 0x2a, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x2f,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x61, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x3a, 0x01, 0x2a, 0x1a, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x56,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73,
	0x68, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_dishes_proto_rawDescOnce sync.Once
	file_api_v1_dishes_proto_rawDescData = file_api_v1_dishes_proto_rawDesc
)

func file_api_v1_dishes_proto_rawDescGZIP() []byte {
	file_api_v1_dishes_proto_rawDescOnce.Do(func() {
		file_api_v1_dishes_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_dishes_proto_rawDescData)
	})
	return file_api_v1_dishes_proto_rawDescData
}

var file_api_v1_dishes_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_dishes_proto_goTypes = []interface{}{
	(*UpdateDishesResponse)(nil), // 0: v1.UpdateDishesResponse
	(*UpdateDishesRequest)(nil),  // 1: v1.UpdateDishesRequest
	(*DelDishesResponse)(nil),    // 2: v1.DelDishesResponse
	(*DelDishesRequest)(nil),     // 3: v1.DelDishesRequest
	(*GetDishesRequest)(nil),     // 4: v1.GetDishesRequest
	(*GetDishesResponse)(nil),    // 5: v1.GetDishesResponse
	(*ListDishesResponse)(nil),   // 6: v1.ListDishesResponse
	(*ListDishesRequest)(nil),    // 7: v1.ListDishesRequest
	(*CreateDishesRequest)(nil),  // 8: v1.CreateDishesRequest
	(*CreateDishesResponse)(nil), // 9: v1.CreateDishesResponse
	(*Dishes)(nil),               // 10: v1.Dishes
}
var file_api_v1_dishes_proto_depIdxs = []int32{
	10, // 0: v1.UpdateDishesResponse.dishes:type_name -> v1.Dishes
	10, // 1: v1.GetDishesResponse.dishes:type_name -> v1.Dishes
	10, // 2: v1.ListDishesResponse.dishes:type_name -> v1.Dishes
	10, // 3: v1.CreateDishesResponse.dishes:type_name -> v1.Dishes
	8,  // 4: v1.DishesService.CreateDishes:input_type -> v1.CreateDishesRequest
	4,  // 5: v1.DishesService.GetDishes:input_type -> v1.GetDishesRequest
	3,  // 6: v1.DishesService.DelDishes:input_type -> v1.DelDishesRequest
	1,  // 7: v1.DishesService.UpdateDishes:input_type -> v1.UpdateDishesRequest
	7,  // 8: v1.DishesService.ListDishes:input_type -> v1.ListDishesRequest
	9,  // 9: v1.DishesService.CreateDishes:output_type -> v1.CreateDishesResponse
	5,  // 10: v1.DishesService.GetDishes:output_type -> v1.GetDishesResponse
	2,  // 11: v1.DishesService.DelDishes:output_type -> v1.DelDishesResponse
	0,  // 12: v1.DishesService.UpdateDishes:output_type -> v1.UpdateDishesResponse
	6,  // 13: v1.DishesService.ListDishes:output_type -> v1.ListDishesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_dishes_proto_init() }
func file_api_v1_dishes_proto_init() {
	if File_api_v1_dishes_proto != nil {
		return
	}
	file_api_v1_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_dishes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_dishes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_dishes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_dishes_proto_goTypes,
		DependencyIndexes: file_api_v1_dishes_proto_depIdxs,
		MessageInfos:      file_api_v1_dishes_proto_msgTypes,
	}.Build()
	File_api_v1_dishes_proto = out.File
	file_api_v1_dishes_proto_rawDesc = nil
	file_api_v1_dishes_proto_goTypes = nil
	file_api_v1_dishes_proto_depIdxs = nil
}
