// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: api/v1/make_steps.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelMakeStepsByDishIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishId string `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
}

func (x *DelMakeStepsByDishIdRequest) Reset() {
	*x = DelMakeStepsByDishIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMakeStepsByDishIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMakeStepsByDishIdRequest) ProtoMessage() {}

func (x *DelMakeStepsByDishIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMakeStepsByDishIdRequest.ProtoReflect.Descriptor instead.
func (*DelMakeStepsByDishIdRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{0}
}

func (x *DelMakeStepsByDishIdRequest) GetDishId() string {
	if x != nil {
		return x.DishId
	}
	return ""
}

type DelMakeStepsByDishIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelMakeStepsByDishIdResponse) Reset() {
	*x = DelMakeStepsByDishIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMakeStepsByDishIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMakeStepsByDishIdResponse) ProtoMessage() {}

func (x *DelMakeStepsByDishIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMakeStepsByDishIdResponse.ProtoReflect.Descriptor instead.
func (*DelMakeStepsByDishIdResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{1}
}

type UpdateMakeStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MakeStep *MakeStep `protobuf:"bytes,1,opt,name=make_step,json=makeStep,proto3" json:"make_step,omitempty"`
}

func (x *UpdateMakeStepsResponse) Reset() {
	*x = UpdateMakeStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMakeStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMakeStepsResponse) ProtoMessage() {}

func (x *UpdateMakeStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMakeStepsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMakeStepsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMakeStepsResponse) GetMakeStep() *MakeStep {
	if x != nil {
		return x.MakeStep
	}
	return nil
}

type UpdateMakeStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DishId  string `protobuf:"bytes,2,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Step    int64  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UpdateMakeStepsRequest) Reset() {
	*x = UpdateMakeStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMakeStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMakeStepsRequest) ProtoMessage() {}

func (x *UpdateMakeStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMakeStepsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMakeStepsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMakeStepsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMakeStepsRequest) GetDishId() string {
	if x != nil {
		return x.DishId
	}
	return ""
}

func (x *UpdateMakeStepsRequest) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *UpdateMakeStepsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DelMakeStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelMakeStepsResponse) Reset() {
	*x = DelMakeStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMakeStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMakeStepsResponse) ProtoMessage() {}

func (x *DelMakeStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMakeStepsResponse.ProtoReflect.Descriptor instead.
func (*DelMakeStepsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{4}
}

type DelMakeStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelMakeStepsRequest) Reset() {
	*x = DelMakeStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMakeStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMakeStepsRequest) ProtoMessage() {}

func (x *DelMakeStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMakeStepsRequest.ProtoReflect.Descriptor instead.
func (*DelMakeStepsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{5}
}

func (x *DelMakeStepsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMakeStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMakeStepsRequest) Reset() {
	*x = GetMakeStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMakeStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakeStepsRequest) ProtoMessage() {}

func (x *GetMakeStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakeStepsRequest.ProtoReflect.Descriptor instead.
func (*GetMakeStepsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{6}
}

func (x *GetMakeStepsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMakeStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MakeStep *MakeStep `protobuf:"bytes,1,opt,name=make_step,json=makeStep,proto3" json:"make_step,omitempty"`
}

func (x *GetMakeStepsResponse) Reset() {
	*x = GetMakeStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMakeStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakeStepsResponse) ProtoMessage() {}

func (x *GetMakeStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakeStepsResponse.ProtoReflect.Descriptor instead.
func (*GetMakeStepsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{7}
}

func (x *GetMakeStepsResponse) GetMakeStep() *MakeStep {
	if x != nil {
		return x.MakeStep
	}
	return nil
}

type DishesMakeStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steps []*MakeStep `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *DishesMakeStepsResponse) Reset() {
	*x = DishesMakeStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishesMakeStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishesMakeStepsResponse) ProtoMessage() {}

func (x *DishesMakeStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishesMakeStepsResponse.ProtoReflect.Descriptor instead.
func (*DishesMakeStepsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{8}
}

func (x *DishesMakeStepsResponse) GetSteps() []*MakeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type DishesMakeStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishId string `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
}

func (x *DishesMakeStepsRequest) Reset() {
	*x = DishesMakeStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishesMakeStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishesMakeStepsRequest) ProtoMessage() {}

func (x *DishesMakeStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishesMakeStepsRequest.ProtoReflect.Descriptor instead.
func (*DishesMakeStepsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{9}
}

func (x *DishesMakeStepsRequest) GetDishId() string {
	if x != nil {
		return x.DishId
	}
	return ""
}

type CreateMakeStepsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DishId string            `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Steps  []*CreateMakeStep `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *CreateMakeStepsRequest) Reset() {
	*x = CreateMakeStepsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMakeStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMakeStepsRequest) ProtoMessage() {}

func (x *CreateMakeStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMakeStepsRequest.ProtoReflect.Descriptor instead.
func (*CreateMakeStepsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMakeStepsRequest) GetDishId() string {
	if x != nil {
		return x.DishId
	}
	return ""
}

func (x *CreateMakeStepsRequest) GetSteps() []*CreateMakeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CreateMakeStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step    int64  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreateMakeStep) Reset() {
	*x = CreateMakeStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMakeStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMakeStep) ProtoMessage() {}

func (x *CreateMakeStep) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMakeStep.ProtoReflect.Descriptor instead.
func (*CreateMakeStep) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMakeStep) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *CreateMakeStep) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMakeStepsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steps []*MakeStep `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *CreateMakeStepsResponse) Reset() {
	*x = CreateMakeStepsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_make_steps_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMakeStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMakeStepsResponse) ProtoMessage() {}

func (x *CreateMakeStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_make_steps_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMakeStepsResponse.ProtoReflect.Descriptor instead.
func (*CreateMakeStepsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_make_steps_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMakeStepsResponse) GetSteps() []*MakeStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

var File_api_v1_make_steps_proto protoreflect.FileDescriptor

var file_api_v1_make_steps_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x5f, 0x73, 0x74,
	0x65, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x4d, 0x61,
	0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x42, 0x79, 0x44, 0x69, 0x73, 0x68, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01,
	0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x4d,
	0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x42, 0x79, 0x44, 0x69, 0x73, 0x68, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x6d, 0x61, 0x6b, 0x65, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65,
	0x53, 0x74, 0x65, 0x70, 0x52, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x22, 0x93,
	0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x20, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x06, 0x64, 0x69,
	0x73, 0x68, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x12, 0x21, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53,
	0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x6d, 0x61, 0x6b, 0x65, 0x5f, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b,
	0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x22,
	0x3d, 0x0a, 0x17, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74,
	0x65, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x22, 0x31,
	0x0a, 0x16, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49,
	0x64, 0x22, 0x6e, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53,
	0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x64,
	0x69, 0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x49, 0x64, 0x12, 0x32, 0x0a,
	0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x22, 0x50, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53,
	0x74, 0x65, 0x70, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70,
	0x12, 0x21, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b,
	0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65,
	0x70, 0x73, 0x32, 0xc1, 0x05, 0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x3a, 0x01, 0x2a, 0x22, 0x18,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x2d, 0x73, 0x74, 0x65,
	0x70, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x65, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74,
	0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b,
	0x65, 0x2d, 0x73, 0x74, 0x65, 0x70, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12,
	0x68, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12,
	0x17, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x2a, 0x1d, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x2d, 0x73, 0x74, 0x65, 0x70, 0x2f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x8a, 0x01, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x42, 0x79, 0x44, 0x69, 0x73, 0x68,
	0x49, 0x64, 0x12, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x53,
	0x74, 0x65, 0x70, 0x73, 0x42, 0x79, 0x44, 0x69, 0x73, 0x68, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65,
	0x53, 0x74, 0x65, 0x70, 0x73, 0x42, 0x79, 0x44, 0x69, 0x73, 0x68, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x2a, 0x27, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x2d, 0x73, 0x74, 0x65, 0x70,
	0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x2f, 0x7b, 0x64, 0x69,
	0x73, 0x68, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x6f, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x3a, 0x01, 0x2a, 0x1a, 0x18, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x2d, 0x73, 0x74, 0x65, 0x70,
	0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x6d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1a, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65,
	0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x2d, 0x73, 0x74, 0x65,
	0x70, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x42, 0x1c, 0x5a, 0x1a, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_make_steps_proto_rawDescOnce sync.Once
	file_api_v1_make_steps_proto_rawDescData = file_api_v1_make_steps_proto_rawDesc
)

func file_api_v1_make_steps_proto_rawDescGZIP() []byte {
	file_api_v1_make_steps_proto_rawDescOnce.Do(func() {
		file_api_v1_make_steps_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_make_steps_proto_rawDescData)
	})
	return file_api_v1_make_steps_proto_rawDescData
}

var file_api_v1_make_steps_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_make_steps_proto_goTypes = []interface{}{
	(*DelMakeStepsByDishIdRequest)(nil),  // 0: v1.DelMakeStepsByDishIdRequest
	(*DelMakeStepsByDishIdResponse)(nil), // 1: v1.DelMakeStepsByDishIdResponse
	(*UpdateMakeStepsResponse)(nil),      // 2: v1.UpdateMakeStepsResponse
	(*UpdateMakeStepsRequest)(nil),       // 3: v1.UpdateMakeStepsRequest
	(*DelMakeStepsResponse)(nil),         // 4: v1.DelMakeStepsResponse
	(*DelMakeStepsRequest)(nil),          // 5: v1.DelMakeStepsRequest
	(*GetMakeStepsRequest)(nil),          // 6: v1.GetMakeStepsRequest
	(*GetMakeStepsResponse)(nil),         // 7: v1.GetMakeStepsResponse
	(*DishesMakeStepsResponse)(nil),      // 8: v1.DishesMakeStepsResponse
	(*DishesMakeStepsRequest)(nil),       // 9: v1.DishesMakeStepsRequest
	(*CreateMakeStepsRequest)(nil),       // 10: v1.CreateMakeStepsRequest
	(*CreateMakeStep)(nil),               // 11: v1.CreateMakeStep
	(*CreateMakeStepsResponse)(nil),      // 12: v1.CreateMakeStepsResponse
	(*MakeStep)(nil),                     // 13: v1.MakeStep
}
var file_api_v1_make_steps_proto_depIdxs = []int32{
	13, // 0: v1.UpdateMakeStepsResponse.make_step:type_name -> v1.MakeStep
	13, // 1: v1.GetMakeStepsResponse.make_step:type_name -> v1.MakeStep
	13, // 2: v1.DishesMakeStepsResponse.steps:type_name -> v1.MakeStep
	11, // 3: v1.CreateMakeStepsRequest.steps:type_name -> v1.CreateMakeStep
	13, // 4: v1.CreateMakeStepsResponse.steps:type_name -> v1.MakeStep
	10, // 5: v1.MakeStepsService.CreateMakeSteps:input_type -> v1.CreateMakeStepsRequest
	6,  // 6: v1.MakeStepsService.GetMakeSteps:input_type -> v1.GetMakeStepsRequest
	5,  // 7: v1.MakeStepsService.DelMakeSteps:input_type -> v1.DelMakeStepsRequest
	0,  // 8: v1.MakeStepsService.DelMakeStepsByDishId:input_type -> v1.DelMakeStepsByDishIdRequest
	3,  // 9: v1.MakeStepsService.UpdateMakeSteps:input_type -> v1.UpdateMakeStepsRequest
	9,  // 10: v1.MakeStepsService.GetDishesMakeSteps:input_type -> v1.DishesMakeStepsRequest
	12, // 11: v1.MakeStepsService.CreateMakeSteps:output_type -> v1.CreateMakeStepsResponse
	7,  // 12: v1.MakeStepsService.GetMakeSteps:output_type -> v1.GetMakeStepsResponse
	4,  // 13: v1.MakeStepsService.DelMakeSteps:output_type -> v1.DelMakeStepsResponse
	1,  // 14: v1.MakeStepsService.DelMakeStepsByDishId:output_type -> v1.DelMakeStepsByDishIdResponse
	2,  // 15: v1.MakeStepsService.UpdateMakeSteps:output_type -> v1.UpdateMakeStepsResponse
	8,  // 16: v1.MakeStepsService.GetDishesMakeSteps:output_type -> v1.DishesMakeStepsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_make_steps_proto_init() }
func file_api_v1_make_steps_proto_init() {
	if File_api_v1_make_steps_proto != nil {
		return
	}
	file_api_v1_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_make_steps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMakeStepsByDishIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMakeStepsByDishIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMakeStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMakeStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMakeStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMakeStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMakeStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMakeStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DishesMakeStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DishesMakeStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMakeStepsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMakeStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_make_steps_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMakeStepsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_make_steps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_make_steps_proto_goTypes,
		DependencyIndexes: file_api_v1_make_steps_proto_depIdxs,
		MessageInfos:      file_api_v1_make_steps_proto_msgTypes,
	}.Build()
	File_api_v1_make_steps_proto = out.File
	file_api_v1_make_steps_proto_rawDesc = nil
	file_api_v1_make_steps_proto_goTypes = nil
	file_api_v1_make_steps_proto_depIdxs = nil
}
