// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1/side_dishes.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSideDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *CreateSideDishesRequest) Reset() {
	*x = CreateSideDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSideDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSideDishesRequest) ProtoMessage() {}

func (x *CreateSideDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSideDishesRequest.ProtoReflect.Descriptor instead.
func (*CreateSideDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSideDishesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSideDishesRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateSideDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SideDishes *SideDishes `protobuf:"bytes,1,opt,name=side_dishes,json=sideDishes,proto3" json:"side_dishes,omitempty"`
}

func (x *CreateSideDishesResponse) Reset() {
	*x = CreateSideDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSideDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSideDishesResponse) ProtoMessage() {}

func (x *CreateSideDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSideDishesResponse.ProtoReflect.Descriptor instead.
func (*CreateSideDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSideDishesResponse) GetSideDishes() *SideDishes {
	if x != nil {
		return x.SideDishes
	}
	return nil
}

type UpdateSideDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *UpdateSideDishesRequest) Reset() {
	*x = UpdateSideDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSideDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSideDishesRequest) ProtoMessage() {}

func (x *UpdateSideDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSideDishesRequest.ProtoReflect.Descriptor instead.
func (*UpdateSideDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSideDishesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSideDishesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSideDishesRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateSideDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SideDishes *SideDishes `protobuf:"bytes,1,opt,name=side_dishes,json=sideDishes,proto3" json:"side_dishes,omitempty"`
}

func (x *UpdateSideDishesResponse) Reset() {
	*x = UpdateSideDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSideDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSideDishesResponse) ProtoMessage() {}

func (x *UpdateSideDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSideDishesResponse.ProtoReflect.Descriptor instead.
func (*UpdateSideDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSideDishesResponse) GetSideDishes() *SideDishes {
	if x != nil {
		return x.SideDishes
	}
	return nil
}

type GetSideDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSideDishesRequest) Reset() {
	*x = GetSideDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSideDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSideDishesRequest) ProtoMessage() {}

func (x *GetSideDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSideDishesRequest.ProtoReflect.Descriptor instead.
func (*GetSideDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{4}
}

func (x *GetSideDishesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSideDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SideDishes *SideDishes `protobuf:"bytes,1,opt,name=side_dishes,json=sideDishes,proto3" json:"side_dishes,omitempty"`
}

func (x *GetSideDishesResponse) Reset() {
	*x = GetSideDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSideDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSideDishesResponse) ProtoMessage() {}

func (x *GetSideDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSideDishesResponse.ProtoReflect.Descriptor instead.
func (*GetSideDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{5}
}

func (x *GetSideDishesResponse) GetSideDishes() *SideDishes {
	if x != nil {
		return x.SideDishes
	}
	return nil
}

type DelSideDishesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DelSideDishesRequest) Reset() {
	*x = DelSideDishesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSideDishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSideDishesRequest) ProtoMessage() {}

func (x *DelSideDishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSideDishesRequest.ProtoReflect.Descriptor instead.
func (*DelSideDishesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{6}
}

func (x *DelSideDishesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DelSideDishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelSideDishesResponse) Reset() {
	*x = DelSideDishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_side_dishes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelSideDishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSideDishesResponse) ProtoMessage() {}

func (x *DelSideDishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_side_dishes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSideDishesResponse.ProtoReflect.Descriptor instead.
func (*DelSideDishesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_side_dishes_proto_rawDescGZIP(), []int{7}
}

var File_api_v1_side_dishes_proto protoreflect.FileDescriptor

var file_api_v1_side_dishes_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x45, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x4b, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x64,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x0a, 0x73, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x4b, 0x0a, 0x18, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x64,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x0a, 0x73, 0x69, 0x64,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x48, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x69, 0x64, 0x65,
	0x5f, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x0a, 0x73,
	0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa9, 0x03, 0x0a, 0x11, 0x53,
	0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x66, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22, 0x0c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x12, 0x66, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a,
	0x01, 0x2a, 0x1a, 0x0c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65,
	0x12, 0x5f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x63, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x69, 0x64, 0x65, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x69, 0x64, 0x65, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x2a,
	0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x64, 0x65,
	0x6c, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x0f, 0x5a, 0x0d, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_side_dishes_proto_rawDescOnce sync.Once
	file_api_v1_side_dishes_proto_rawDescData = file_api_v1_side_dishes_proto_rawDesc
)

func file_api_v1_side_dishes_proto_rawDescGZIP() []byte {
	file_api_v1_side_dishes_proto_rawDescOnce.Do(func() {
		file_api_v1_side_dishes_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_side_dishes_proto_rawDescData)
	})
	return file_api_v1_side_dishes_proto_rawDescData
}

var file_api_v1_side_dishes_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_side_dishes_proto_goTypes = []interface{}{
	(*CreateSideDishesRequest)(nil),  // 0: v1.CreateSideDishesRequest
	(*CreateSideDishesResponse)(nil), // 1: v1.CreateSideDishesResponse
	(*UpdateSideDishesRequest)(nil),  // 2: v1.UpdateSideDishesRequest
	(*UpdateSideDishesResponse)(nil), // 3: v1.UpdateSideDishesResponse
	(*GetSideDishesRequest)(nil),     // 4: v1.GetSideDishesRequest
	(*GetSideDishesResponse)(nil),    // 5: v1.GetSideDishesResponse
	(*DelSideDishesRequest)(nil),     // 6: v1.DelSideDishesRequest
	(*DelSideDishesResponse)(nil),    // 7: v1.DelSideDishesResponse
	(*SideDishes)(nil),               // 8: v1.SideDishes
}
var file_api_v1_side_dishes_proto_depIdxs = []int32{
	8, // 0: v1.CreateSideDishesResponse.side_dishes:type_name -> v1.SideDishes
	8, // 1: v1.UpdateSideDishesResponse.side_dishes:type_name -> v1.SideDishes
	8, // 2: v1.GetSideDishesResponse.side_dishes:type_name -> v1.SideDishes
	0, // 3: v1.SideDishesService.CreateSideDishes:input_type -> v1.CreateSideDishesRequest
	2, // 4: v1.SideDishesService.UpdateSideDishes:input_type -> v1.UpdateSideDishesRequest
	4, // 5: v1.SideDishesService.GetSideDishes:input_type -> v1.GetSideDishesRequest
	6, // 6: v1.SideDishesService.DelSideDishes:input_type -> v1.DelSideDishesRequest
	1, // 7: v1.SideDishesService.CreateSideDishes:output_type -> v1.CreateSideDishesResponse
	3, // 8: v1.SideDishesService.UpdateSideDishes:output_type -> v1.UpdateSideDishesResponse
	5, // 9: v1.SideDishesService.GetSideDishes:output_type -> v1.GetSideDishesResponse
	7, // 10: v1.SideDishesService.DelSideDishes:output_type -> v1.DelSideDishesResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_side_dishes_proto_init() }
func file_api_v1_side_dishes_proto_init() {
	if File_api_v1_side_dishes_proto != nil {
		return
	}
	file_api_v1_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_side_dishes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSideDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSideDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSideDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSideDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSideDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSideDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSideDishesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_side_dishes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelSideDishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_side_dishes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_side_dishes_proto_goTypes,
		DependencyIndexes: file_api_v1_side_dishes_proto_depIdxs,
		MessageInfos:      file_api_v1_side_dishes_proto_msgTypes,
	}.Build()
	File_api_v1_side_dishes_proto = out.File
	file_api_v1_side_dishes_proto_rawDesc = nil
	file_api_v1_side_dishes_proto_goTypes = nil
	file_api_v1_side_dishes_proto_depIdxs = nil
}
