server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/order-dishes?charset=utf8&parseTime=True&loc=Local
#  redis:
#    addr: redis:6379
#    read_timeout: 1s
#    write_timeout: 2s
#  consul:
#    address: consul:8500
#    scheme: http