// Code generated by boot. DO NOT EDIT.

package dao

import (
	"context"

	model "dishes/order-dishes/internal/dao/model"
	"github.com/Rascal0814/boot/log"
	"github.com/Rascal0814/boot/orm"
	"gorm.io/gorm"
)

type DishDao struct {
	db  *gorm.DB
	log *log.Logger
}

func NewDishDao(db *gorm.DB, log *log.Logger) *DishDao {
	return &DishDao{db: db, log: log}
}

func (dao *DishDao) Insert(ctx context.Context, f func(m *model.Dish) error) (*model.Dish, error) {
	var m model.Dish
	err := f(&m)
	if err != nil {
		return nil, dao.log.Error("insert Dish error", err)
	}
	err = dao.db.WithContext(ctx).Create(&m).Error
	if err != nil {
		return nil, dao.log.Error("insert Dish error", err)
	}
	return &m, err
}

func (dao *DishDao) Get(ctx context.Context, id int64) (*model.Dish, error) {
	var m = &model.Dish{}
	err := dao.db.WithContext(ctx).Where("id = ?", id).First(m).Error
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (dao *DishDao) Del(ctx context.Context, id int64) error {
	err := dao.db.WithContext(ctx).Where("id = ?", id).Delete(&model.Dish{}).Error
	if err != nil {
		return dao.log.Error("del Dish error", err)
	}
	return nil
}

func (dao *DishDao) List(ctx context.Context,p *orm.Pager) ([]*model.Dish, int64, error) {
	var res = make([]*model.Dish, 0)
	var total int64
	err := dao.db.WithContext(ctx).Model(&model.Dish{}).Count(&total).Limit(int((p.PageIndex) * p.PageSize)).Offset(int(p.PageIndex - 1)).Find(&res).Error
	if err != nil {
		return nil, 0, dao.log.Error("get Dish list error", err)
	}
	return res, total, nil
}

func (dao *DishDao) Update(ctx context.Context, m *model.Dish) (*model.Dish, error) {
	err := dao.db.WithContext(ctx).Updates(m).Error
	if err != nil {
		return nil, dao.log.Error("update Dish error", err)
	}
	return m, nil
}
