// Code generated by boot. DO NOT EDIT.

package dao

import (
	"context"

	model "dishes/order-dishes/internal/dao/model"
	"github.com/Rascal0814/boot/log"
	"github.com/Rascal0814/boot/orm"
	"gorm.io/gorm"
)

type OrderDao struct {
	db  *gorm.DB
	log *log.Logger
}

func NewOrderDao(db *gorm.DB, log *log.Logger) *OrderDao {
	return &OrderDao{db: db, log: log}
}

func (dao *OrderDao) Insert(ctx context.Context, f func(m *model.Order) error) (*model.Order, error) {
	var m model.Order
	err := f(&m)
	if err != nil {
		return nil, dao.log.Error("insert Order error", err)
	}
	err = dao.db.WithContext(ctx).Create(&m).Error
	if err != nil {
		return nil, dao.log.Error("insert Order error", err)
	}
	return &m, err
}

func (dao *OrderDao) Get(ctx context.Context, id int64) (*model.Order, error) {
	var m = &model.Order{}
	err := dao.db.WithContext(ctx).Where("id = ?", id).Find(m).Error
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (dao *OrderDao) Del(ctx context.Context, id int64) error {
	err := dao.db.WithContext(ctx).Where("id = ?", id).Delete(&model.Order{}).Error
	if err != nil {
		return dao.log.Error("del Order error", err)
	}
	return nil
}

func (dao *OrderDao) List(ctx context.Context,p *orm.Pager) ([]*model.Order, int64, error) {
	var res = make([]*model.Order, 0)
	var total int64
	err := dao.db.WithContext(ctx).Model(&model.Order{}).Count(&total).Limit(int((p.PageIndex) * p.PageSize)).Offset(int(p.PageIndex - 1)).Find(&res).Error
	if err != nil {
		return nil, 0, dao.log.Error("get Order list error", err)
	}
	return res, total, nil
}

func (dao *OrderDao) Update(ctx context.Context, m *model.Order) (*model.Order, error) {
	err := dao.db.WithContext(ctx).Updates(m).Error
	if err != nil {
		return nil, dao.log.Error("update Order error", err)
	}
	return m, nil
}
