// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDish = "dishes"

// Dish mapped from table <dishes>
type Dish struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	Name      string         `gorm:"column:name;not null" json:"name"`                                       // 名称
	Logo      string         `gorm:"column:logo;not null" json:"logo"`                                       // logo
	Remark    string         `gorm:"column:remark;not null" json:"remark"`                                   // 备注
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 是否已删除
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	Version   int64          `gorm:"column:_version;not null" json:"_version"`                               // 数据库记录更新的乐观锁
}

// TableName Dish's table name
func (*Dish) TableName() string {
	return TableNameDish
}
